# Run Scripts/Analyses/Analysis_mod2.R 
# to obtain the required model output results

md <- readRDS("Model_output/Mod2_results.RDS")

post_mat <- as.data.frame(as.matrix(md))

summ_ci <- function(x, digits = 3) {
  q <- unname(quantile(as.numeric(x), c(0.025, 0.5, 0.975), na.rm = TRUE))
  sprintf("%.*f\\;[%.*f,\\;%.*f]",
          digits, q[2], digits, q[1], digits, q[3])
}

diff_ci <- function(x, y, digits = 3) {
  q <- unname(quantile(as.numeric(x) - as.numeric(y),
                       c(0.025, 0.5, 0.975), na.rm = TRUE))
  sprintf("%.*f\\;[%.*f,\\;%.*f]",
          digits, q[2], digits, q[1], digits, q[3])
}

dash <- "--"

latex_lines <- c(
  "\\begin{table}[ht]",
  "\\caption{Posterior medians and 95\\% credible intervals}",
  "\\centering",
  "\\small",
  "\\begin{tabular}{lccc}",
  "\\hline",
  "\\textbf{Parameter} & \\textbf{Small group} & \\textbf{Large group} & \\textbf{Difference (S--L)} \\\\",
  "\\hline",
  "\\multicolumn{4}{l}{\\textbf{Fixed effects}} \\\\",
  paste0("$\\mu_0$ Intercept & ",
         summ_ci(post_mat$mean_feed1), " & ",
         summ_ci(post_mat$mean_feed2), " & ",
         diff_ci(post_mat$mean_feed1, post_mat$mean_feed2), " \\\\"),
  "\\multicolumn{4}{l}{\\,\\,\\,\\textit{Experimental controls}} \\\\",
  paste0("$\\beta_1$ Test day (1st or 2nd) (Day) & ",
         summ_ci(post_mat[["b1[1]"]]), " & ", dash, " & ", dash, " \\\\"),
  paste0("$\\beta_2$ Assay order (Seq) & ",
         summ_ci(post_mat[["b1[2]"]]), " & ",
         summ_ci(post_mat[["b2[1]"]]), " & ",
         diff_ci(post_mat[["b1[2]"]], post_mat[["b2[1]"]]), " \\\\"),
  paste0("$\\beta_3$ Large group assay first (Grp) & ",
         summ_ci(post_mat[["b1[3]"]]), " & ",
         summ_ci(post_mat[["b2[2]"]]), " & ",
         diff_ci(post_mat[["b1[3]"]], post_mat[["b2[2]"]]), " \\\\"),
  paste0("$\\beta_4$ Day*Seq & ",
         summ_ci(post_mat[["b1[4]"]]), " & ", dash, " & ", dash, " \\\\"),
  paste0("$\\beta_5$ Day*Grp & ",
         summ_ci(post_mat[["b1[5]"]]), " & ", dash, " & ", dash, " \\\\"),
  paste0("$\\beta_6$ Seq*Grp & ",
         summ_ci(post_mat[["b1[6]"]]), " & ",
         summ_ci(post_mat[["b2[3]"]]), " & ",
         diff_ci(post_mat[["b1[6]"]], post_mat[["b2[3]"]]), " \\\\"),
  paste0("$\\beta_7$ Day*Seq*Grp & ",
         summ_ci(post_mat[["b1[7]"]]), " & ", dash, " & ", dash, " \\\\"),
  paste0("Focal foraging events & ",
         summ_ci(post_mat$beta_events1), " & ",
         summ_ci(post_mat$beta_events2), " & ",
         diff_ci(post_mat$beta_events1,
                 post_mat$beta_events2), " \\\\"),
  paste0("Partner foraging events & ",
         summ_ci(post_mat$beta_events_opp1), " & ",
         summ_ci(post_mat$beta_events_opp2), " & ",
         diff_ci(post_mat$beta_events_opp1,
                 post_mat$beta_events_opp2), " \\\\"),
  "\\multicolumn{4}{l}{\\,\\,\\,\\textit{Effects of tactic use}} \\\\",
  paste0("Focal scrounging & ",
         summ_ci(post_mat$beta_focal1), " & ",
         summ_ci(post_mat$beta_focal2), " & ",
         diff_ci(post_mat$beta_focal1, post_mat$beta_focal2), " \\\\"),
  paste0("Partner scrounging & ",
         summ_ci(post_mat$beta_opp1), " & ",
         summ_ci(post_mat$beta_opp2), " & ",
         diff_ci(post_mat$beta_opp1, post_mat$beta_opp2), " \\\\"),
  paste0("Focal scrounging$^2$ & ",
         summ_ci(post_mat$beta_focal_sq1), " & ",
         summ_ci(post_mat$beta_focal_sq2), " & ",
         diff_ci(post_mat$beta_focal_sq1, post_mat$beta_focal_sq2), " \\\\"),
  paste0("Partner scrounging$^2$ & ",
         summ_ci(post_mat$beta_opp_sq1), " & ",
         summ_ci(post_mat$beta_opp_sq2), " & ",
         diff_ci(post_mat$beta_opp_sq1, post_mat$beta_opp_sq2), " \\\\"),
  paste0("Focal $\\times$ Partner & ",
         summ_ci(post_mat$beta_int1), " & ",
         summ_ci(post_mat$beta_int2), " & ",
         diff_ci(post_mat$beta_int1, post_mat$beta_int2), " \\\\"),
  "\\hline",
  "\\multicolumn{4}{l}{\\textbf{Random effects}} \\\\",
  paste0("$V_{\\text{ID}}$ & ",
         summ_ci(post_mat$V_I1), " & ",
         summ_ci(post_mat$V_I2), " & ",
         diff_ci(post_mat$V_I1, post_mat$V_I2), " \\\\"),
  paste0("$V_{\\text{AssayID}}$ & ",
         summ_ci(post_mat$V_Trial1), " & ",
         summ_ci(post_mat$V_Trial2), " & ",
         diff_ci(post_mat$V_Trial1, post_mat$V_Trial2), " \\\\"),
  paste0("$V_{\\text{GroupID}}$ & ",
         summ_ci(post_mat$V_Group1), " & ",
         summ_ci(post_mat$V_Group2), " & ",
         diff_ci(post_mat$V_Group1, post_mat$V_Group2), " \\\\"),
  paste0("$V_{\\text{Residual}}$ & ",
         summ_ci(post_mat$V_e1), " & ",
         summ_ci(post_mat$V_e2), " & ",
         diff_ci(post_mat$V_e1, post_mat$V_e2), " \\\\"),
  paste0("$V_{\\text{Total}}$ & ",
         summ_ci(post_mat$V_total1), " & ",
         summ_ci(post_mat$V_total2), " & ",
         diff_ci(post_mat$V_total1, post_mat$V_total2), " \\\\"),
  "\\hline",
  "\\multicolumn{4}{l}{\\textbf{Repeatabilities}} \\\\",
  paste0("$VC_{\\text{ID}}$ & ",
         summ_ci(post_mat$VC_I1), " & ",
         summ_ci(post_mat$VC_I2), " & ",
         diff_ci(post_mat$VC_I1, post_mat$VC_I2), " \\\\"),
  paste0("$VC_{\\text{AssayID}}$ & ",
         summ_ci(post_mat$VC_Trial1), " & ",
         summ_ci(post_mat$VC_Trial2), " & ",
         diff_ci(post_mat$VC_Trial1, post_mat$VC_Trial2), " \\\\"),
  paste0("$VC_{\\text{GroupID}}$ & ",
         summ_ci(post_mat$VC_Group1), " & ",
         summ_ci(post_mat$VC_Group2), " & ",
         diff_ci(post_mat$VC_Group1, post_mat$VC_Group2), " \\\\"),
  paste0("$VC_{\\text{Residual}}$ & ",
         summ_ci(post_mat$VC_e1), " & ",
         summ_ci(post_mat$VC_e2), " & ",
         diff_ci(post_mat$VC_e1, post_mat$VC_e2), " \\\\"),
  "\\hline",
  "\\multicolumn{4}{l}{\\textbf{Correlations}} \\\\",
  paste0("$\\mathrm{cor}(\\text{ID}_{small},\\text{ID}_{large})$ & \\multicolumn{2}{c}{",
         summ_ci(post_mat$cor_int1_int2),
         "} & \\multicolumn{1}{c}{--} \\\\"),
  "\\hline",
  "\\end{tabular}",
  "\\label{tab:results_foraging_success}",
  "\\end{table}"
)

cat(paste(latex_lines, collapse = "\n"))
